framework:
  messenger:
    transports:
      async: 'doctrine://default?auto_setup=1'
      sync: 'sync://'

when@test:
  framework:
    messenger:
      transports:
        async: 'test://'
        scheduler_default: 'test://'
        scheduler_server: 'test://'

