services:
  postgres:
    image: postgres:16.6
    container_name: hyvor-relay-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: hyvor_relay
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hyvor_relay"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    image: hyvor/relay:latest
    container_name: hyvor-relay
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: "host"
    env_file:
      - .env

volumes:
  postgres_data:
